fix up unexpected situation with fontconfig in our packages
git-svn-id: svn://localhost/ardour2/branches/3.0@12190 d708f5d6-7413-0410-9779-e7cbd77b26cf

diff --git a/tools/linux_packaging/build b/tools/linux_packaging/build
--- a/tools/linux_packaging/build
+++ b/tools/linux_packaging/build
@@ -280,6 +280,25 @@ else
 	echo "Skipping NLS support"
 fi
 
+### Find fontconfig ###
+FCROOT=`pkg-config --libs-only-L fontconfig | sed -e "s/-L//" -e "s/[[:space:]]//g"`
+if [ ! -z "$FCROOT" ]; then
+	echo "Found FCOOT using pkg-config"
+        FCETC=`dirname $FCROOT`/etc
+elif [ -d /usr/lib/gtk-2.0 ]; then
+	FCETC="/etc"
+elif [ -d /usr/local/lib/gtk-2.0 ]; then
+	FCETC="/usr/local/etc"
+else
+	echo ""
+	echo "!!! ERROR !!! - Unable to locate fontconfig directory. Packager will exit"
+	echo ""
+	exit 1
+fi
+
+echo "Copying Fontconfig files to $Etc ..."
+cp -r $FCETC/fonts $Etc
+
 ### Find gtk ###
 GTKROOT=`pkg-config --libs-only-L gtk+-2.0 | sed -e "s/-L//" -e "s/[[:space:]]//g"`
 if [ ! -z "$GTKROOT" ]; then
