linux-installer: gcc4/5 warning.

diff --git a/tools/linux_packaging/build b/tools/linux_packaging/build
--- a/tools/linux_packaging/build
+++ b/tools/linux_packaging/build
@@ -32,6 +32,7 @@ WITH_NLS=
 EXTERNAL_JACK=
 VENDOR=Ardour ;
 EXENAME=ardour
+GCC5ABI=false
 BUILDTYPE=""
 
 
@@ -86,6 +87,7 @@ while [ $# -gt 0 ] ; do
 	--sysdeps) PRINT_SYSDEPS=1; shift ;;
 	--nls) WITH_NLS=1 ; shift ;;
 	--harvid) WITH_HARVID=1 ; shift ;;
+	--gcc5abi) GCC5ABI=true ; shift ;;
 
 	*)
 		#catch all for unknown arguments
@@ -655,9 +657,17 @@ chmod a+x $APPBIN/${APP_VER_NAME}.uninstall.sh
 #
 # Add the stage2.run script
 #
-sed -e "s/%REPLACE_MAJOR_VERSION%/${major_version}/;s/%REPLACE_PGM%/${APPNAME}/;s/%REPLACE_VENDOR%/${VENDOR}/;s/%REPLACE_EXE%/${EXENAME}/" < stage2.run.in > stage2.run
+sed -e "s/%REPLACE_MAJOR_VERSION%/${major_version}/;s/%REPLACE_PGM%/${APPNAME}/;s/%REPLACE_VENDOR%/${VENDOR}/;s/%REPLACE_EXE%/${EXENAME}/;s/%REPLACE_GCC5%/${GCC5ABI}" < stage2.run.in > stage2.run
 chmod a+x stage2.run
 
+
+# gcc4/5 ABI test tool
+if [ -e $BUILD_ROOT/tools/gccabicheck/gcc-glibmm-abi-check]; then
+	cp $BUILD_ROOT/tools/gccabicheck/gcc-glibmm-abi-check $APPBIN
+else
+	echo "!!!ERROR !!! gcc-glibmm-abi-check program is missing. packager will exit without being complete"
+	exit 1
+fi
 
 #Sanity Check file
 if [ -e $BUILD_ROOT/tools/sanity_check/sanityCheck ]; then
