gcc ABI check happens before unpacking

diff --git a/tools/linux_packaging/package b/tools/linux_packaging/package
--- a/tools/linux_packaging/package
+++ b/tools/linux_packaging/package
@@ -10,7 +10,7 @@ SINGLE_ARCH="F"
 X86_BUNDLE_OK="F"
 X86_64_BUNDLE_OK="F"
 MAKESELF=""
-
+BUILD_ROOT=../../build
 
 if [ $# -eq 0 ] ; then
 	echo ""	 
@@ -161,6 +161,16 @@ fi
 cp install.sh ${PACKAGE}
 cp stage2.run ${PACKAGE}/.stage2.run
 cp README ${PACKAGE}
+
+# gcc4/5 ABI test tool
+if [ -e $BUILD_ROOT/tools/gccabicheck/gcc-glibmm-abi-check ]; then
+	cp $BUILD_ROOT/tools/gccabicheck/gcc-glibmm-abi-check ${PACKAGE}/.gcc-glibmm-abi-check
+else
+	echo "!!!ERROR !!! gcc-glibmm-abi-check program is missing. packager will exit without being complete"
+	rm -rf ${PACKAGE}
+	rm -f stage2.run
+	exit 1
+fi
 
 if test -n "$MAKESELF"; then
 	echo "Creating self-extracting installer"
