fun hacks for wine
windows-VST? yes, we could.

diff --git a/tools/linux_packaging/stage2.run.in b/tools/linux_packaging/stage2.run.in
--- a/tools/linux_packaging/stage2.run.in
+++ b/tools/linux_packaging/stage2.run.in
@@ -313,6 +313,19 @@ else
 	fi
 fi
 
+if %REPLACE_WINE%; then
+	if -z "`which wine`"; then
+		echo ""
+		echo "!!! ERROR !!! - 'wine' was not found."
+		echo ""
+		echo "This version of Ardour with Windows VST support requires wine."
+		echo "https://www.winehq.org/"
+		echo ""
+		read -p "Press ENTER to exit installer:" BLAH
+		exit 1
+	fi
+fi
+
 #####################
 # Unpack the bundle
 #####################
@@ -373,6 +386,46 @@ if [ -z "$XDG_ICON_VER" ];
 then
 	echo "System does not have xdg-icon-resource installed"
 	HAS_XDG="F"
+fi
+
+#################################################
+# Set up libwine.so
+#################################################
+if %REPLACE_WINE%; then
+	echo ""
+	echo "Searching for libwine.so (Windows VST support)"
+	echo ""
+	# we need to add libwine to ardour's LD_LIBRARY_PATH
+	# libwine itself includes paths to the various system-components
+	# which may be different on each platform.
+	#
+	# There's some chicken/egg here: ardour.exe.so is linked against libwine.so
+	# at build-time. wine/wineloader assumes a windows-application (which does not use libwine
+	# directly) and does not set up the LD path to libwine itself. the application terminates
+	# (missing libs) before it even starts..
+	#
+	# wine itself does not provide means to find the location of libwine.
+	# /usr/bin/wine is usually shell-script and libwine.so can be found in
+	# various places on different distros.
+	#
+	# if this check were quick and easy.. it should be done in the startup-script, but it's not
+	# so here we go... (updating wine may require re-installing ardour)
+	#
+	LIBWINE=$(
+		LD_DEBUG=files wine `pwd`/${BUNDLE_DIR}/lib/ardour-vst-scanner.exe.so 2>&1 \
+						 | grep -e "calling init:.*libwine" \
+						 | sed 's/^.*calling init: //' \
+						 | uniq \
+			)
+	if ! test -f "$LIBWINE"; then
+		echo ""
+		echo "!!! ERROR !!! - 'libwine.so*' was not found."
+		echo ""
+		read -p "Press ENTER to exit installer:" BLAH
+		exit 1
+	fi
+  # this replaces/overwrites the bundled libwine
+	cp -L "$LIBWINE" `pwd`/${BUNDLE_DIR}/lib/libwine.so.1
 fi
 
 #################################################
