patch for ugliness in libsndfile 1.0.25, and dir for this and similar future patches
git-svn-id: svn://localhost/ardour2/branches/2.0-ongoing@12372 d708f5d6-7413-0410-9779-e7cbd77b26cf

diff --git a/tools/build-ardour-stack b/tools/build-ardour-stack
--- a/tools/build-ardour-stack
+++ b/tools/build-ardour-stack
@@ -284,16 +284,18 @@ fi
 tar xf libvorbis-1.3.2.tar.bz2 && \
     (set -e && cd libvorbis-1.3.2 && CXXFLAGS="$GLOBAL_CFLAGS" CFLAGS="$GLOBAL_CFLAGS" LDFLAGS="$GLOBAL_LDFLAGS" ./configure --prefix=$PREFIX && make && make install) || die "vorbis build failed"
 
+sndfile_patch=`ls $this_script_dir/misc-patches/libsndfile-1.0.25.patch`
+
 if [ x$OSX != x ] ; then
     # sndfile-play incorrectly includes <Carbon.h> which no longer works on Lion
     tar xf libsndfile-1.0.25.tar.gz && \
-        (set -e && cd libsndfile-1.0.25 && CFLAGS="$GLOBAL_CFLAGS -I/System/Library/Frameworks/Carbon.framework/Headers" LDFLAGS="$GLOBAL_LDFLAGS" ./configure --prefix=$PREFIX --disable-silent-rules && make && make install) || die "sndfile build failed"
+        (set -e && cd libsndfile-1.0.25 && patch -p0 < $sndfile_patch CFLAGS="$GLOBAL_CFLAGS -I/System/Library/Frameworks/Carbon.framework/Headers" LDFLAGS="$GLOBAL_LDFLAGS" ./configure --prefix=$PREFIX --disable-silent-rules && make && make install) || die "sndfile build failed"
     # samplerate incorrectly includes <Carbon.h> which no longer works on Lion
 tar xf libsamplerate-0.1.8.tar.gz && \
     (set -e && cd libsamplerate-0.1.8 && CFLAGS="$GLOBAL_CFLAGS -I/System/Library/Frameworks/Carbon.framework/Headers" LDFLAGS="$GLOBAL_LDFLAGS" ./configure --prefix=$PREFIX && make && make install) || die "samplerate build failed"
 else 
     tar xf libsndfile-1.0.25.tar.gz && \
-        (set -e && cd libsndfile-1.0.25 && CFLAGS="$GLOBAL_CFLAGS" LDFLAGS="$GLOBAL_LDFLAGS" ./configure --prefix=$PREFIX --disable-silent-rules && make && make install) || die "sndfile build failed"
+        (set -e && cd libsndfile-1.0.25 && patch -p0 $sndfile_patch && CFLAGS="$GLOBAL_CFLAGS" LDFLAGS="$GLOBAL_LDFLAGS" ./configure --prefix=$PREFIX --disable-silent-rules && make && make install) || die "sndfile build failed"
     tar xf libsamplerate-0.1.8.tar.gz && \
         (set -e && cd libsamplerate-0.1.8 && CFLAGS="$GLOBAL_CFLAGS" LDFLAGS="$GLOBAL_LDFLAGS" ./configure --prefix=$PREFIX && make && make install) || die "samplerate build failed"
 fi
