final (?!) fixes to dependency stack scripts
git-svn-id: svn://localhost/ardour2/branches/2.0-ongoing@12147 d708f5d6-7413-0410-9779-e7cbd77b26cf

diff --git a/tools/build-ardour-stack b/tools/build-ardour-stack
--- a/tools/build-ardour-stack
+++ b/tools/build-ardour-stack
@@ -71,7 +71,7 @@ if [ ! -f libsigc++-2.2.10.tar.xz ] ; then
 fi
 if [ ! -f glibmm-2.32.0.tar.xz ] ; then
     echo glibmm
-    curl -LO http://ftp.gnome.org/pub/GNOME/sources/glibmm/2.30/glibmm-2.30.1.tar.xz
+    curl -LO http://ftp.gnome.org/pub/GNOME/sources/glibmm/2.32/glibmm-2.32.0.tar.xz
 fi
 if [ ! -f cairomm-1.10.0.tar.gz ] ; then
     echo cairomm
@@ -159,6 +159,31 @@ if [ ! -d LRDF ] ; then
     git clone git://github.com/swh/LRDF.git
 fi
 
+if [ ! -f lv2-1.0.0.tar.bz2 ] ; then
+    echo LV2
+    curl -LO http://lv2plug.in/spec/lv2-1.0.0.tar.bz2
+fi
+if [ ! -f serd-0.14.0.tar.bz2 ] ; then
+    echo Serd
+    curl -LO http://download.drobilla.net/serd-0.14.0.tar.bz2
+fi
+if [ ! -f sord-0.8.0.tar.bz2 ] ; then
+    echo Sord
+    curl -LO http://download.drobilla.net/sord-0.8.0.tar.bz2
+fi
+if [ ! -f sratom-0.2.0.tar.bz2 ] ; then
+    echo Sratom
+    curl -LO http://download.drobilla.net/sratom-0.2.0.tar.bz2
+fi
+if [ ! -f lilv-0.14.2.tar.bz2 ] ; then
+    echo Lilv
+    curl -LO http://download.drobilla.net/lilv-0.14.2.tar.bz2
+fi
+if [ ! -f suil-0.6.0.tar.bz2 ] ; then
+    echo Suil
+    curl -LO http://download.drobilla.net/suil-0.6.0.tar.bz2
+fi
+
 tar xf boost_1_49_0.tar.bz2 && \
   (set -e && cd boost_1_49_0 && ./bootstrap.sh --prefix=$PREFIX --with-libraries=exception && ./b2 && ./b2 install) || die "boost build failed"
 
@@ -167,8 +192,8 @@ tar xf fftw-3.3.1.tar.gz && \
 
 tar xf libsigc++-2.2.10.tar.xz && \
     (set -e && cd libsigc++-2.2.10 && CXXFLAGS="$GLOBAL_CFLAGS" CFLAGS="$GLOBAL_CFLAGS" LDFLAGS="$GLOBAL_LDFLAGS" ./configure --prefix=$PREFIX && make && make install) || die "sigc++ build failed"
-tar xf glibmm-2.30.1.tar.xz && \
-    (set -e && cd glibmm-2.30.1 && CXXFLAGS="$GLOBAL_CFLAGS" CFLAGS="$GLOBAL_CFLAGS" LDFLAGS="$GLOBAL_LDFLAGS" ./configure --prefix=$PREFIX && make && make install) || die "glibmm build failed"
+tar xf glibmm-2.32.0.tar.xz && \
+    (set -e && cd glibmm-2.32.0 && CXXFLAGS="$GLOBAL_CFLAGS" CFLAGS="$GLOBAL_CFLAGS" LDFLAGS="$GLOBAL_LDFLAGS" ./configure --prefix=$PREFIX && make && make install) || die "glibmm build failed"
 tar xf cairomm-1.10.0.tar.gz && \
     (set -e && cd cairomm-1.10.0 && CXXFLAGS="$GLOBAL_CFLAGS" CFLAGS="$GLOBAL_CFLAGS" LDFLAGS="$GLOBAL_LDFLAGS" ./configure --prefix=$PREFIX && make && make install) || die "cairomm build failed"
 tar xf pangomm-2.28.4.tar.xz && \
@@ -232,25 +257,18 @@ tar xf isodate-0.4.0.tar.gz && \
   sed 's/glibtoolize/libtoolize/g' < autogen.sh > ag.sh && mv ag.sh autogen.sh && \
   CFLAGS="$GLOBAL_CFLAGS" LDFLAGS="$GLOBAL_LDFLAGS" sh ./autogen.sh --prefix=$PREFIX && make && make install) || die "LRDF build failed"
 
-# LV2 from svn - note: this doesn't exit with the correct exit code no matter what, plus a bug in waf prevents the use
-# of MACOSX_DEPLOYMENT_TARGET which probably doesn't matter since this isn't using Carbon/Cocoa APIs.
-(if [ ! -d lv2-svn ] ; then svn co http://lv2plug.in/repo/trunk lv2-svn ; fi &&  \
-    cd lv2-svn && unset MACOSX_DEPLOYMENT_TARGET && ./waf configure --prefix=$PREFIX --copy-headers && ./waf && sudo ./waf install) || die "lv2-svn build failed"
-
-#
-# drobilla stuff is from svn for now
-#
-
-(if [ ! -d serd ] ; then mkdir serd ; fi && cd serd && svn co http://svn.drobilla.net/serd/trunk)  && \
-    (set -e && cd serd/trunk && ./waf configure --prefix=$PREFIX && ./waf && ./waf install) || die "serd build failed"
-(if [ ! -d sord ] ; then mkdir sord ; fi && cd sord && svn co http://svn.drobilla.net/sord/trunk)  && \
-    (set -e && cd sord/trunk && ./waf configure --prefix=$PREFIX && ./waf && ./waf install) || die "sord build failed"
-(if [ ! -d sratom ] ; then mkdir sratom ; fi && svn co http://svn.drobilla.net/lad/trunk/sratom)  && \
-    (set -e && cd sratom && ./waf configure --prefix=$PREFIX && ./waf && ./waf install) || die "sratom build failed"
-svn co http://svn.drobilla.net/lad/trunk/lilv && \
-    (set -e && cd lilv && ./waf configure --prefix=$PREFIX && ./waf && ./waf install) || die "lilv build failed"
-svn co http://svn.drobilla.net/lad/trunk/suil && \
-    (set -e && cd suil && CFLAGS="-I$PREFIX/include" ./waf configure --prefix=$PREFIX && ./waf && ./waf install) || die "suil build failed"
+tar xf lv2-1.0.0.tar.bz2 && \
+    (set -e && cd lv2-1.0.0 && unset MACOSX_DEPLOYMENT_TARGET && ./waf configure --prefix=$PREFIX --copy-headers && ./waf build && sudo ./waf install) || die "LV2 build failed"
+tar xf serd-0.14.0.tar.bz2 && \
+    (set -e && cd serd-0.14.0 && ./waf configure --prefix=$PREFIX && ./waf build && ./waf install) || die "serd build failed"
+tar xf sord-0.8.0.tar.bz2 && \
+    (set -e && cd sord-0.8.0 && ./waf configure --prefix=$PREFIX  && ./waf build && ./waf install) || die "sord build failed"
+tar xf sratom-0.2.0.tar.bz2 && \
+    (set -e && cd sratom-0.2.0 && ./waf configure --prefix=$PREFIX && ./waf build && ./waf install) || die "sratom build failed"
+tar xf lilv-0.14.2.tar.bz2 && \
+    (set -e && cd lilv-0.14.2 && ./waf configure --prefix=$PREFIX && ./waf build && ./waf install) || die "lilv build failed"
+tar xf suil-0.6.0.tar.bz2 && \
+    (set -e && cd suil-0.6.0 && CFLAGS="-I$PREFIX/include" ./waf configure --prefix=$PREFIX && ./waf && ./waf install) || die "suil build failed"
 
 # two post-install hacks
 
diff --git a/tools/build-gtk-stack b/tools/build-gtk-stack
--- a/tools/build-gtk-stack
+++ b/tools/build-gtk-stack
@@ -95,7 +95,7 @@ if [ ! -f autoconf-2.68.tar.bz2 ] ; then
 fi
 if [ ! -f libtool-2.4.2.tar.gz ] ; then
     echo libtool
-    curl -LO http://mirrors.ibiblio.org/pub/mirrors/gnu/ftp/gnu/libtool/libtool-2.4.2.tar.gz
+    curl -LO http://ftp.gnu.org/gnu/libtool/libtool-2.4.2.tar.gz
 fi
 if [ ! -f make-3.82.tar.bz2 ] ; then
     echo make
@@ -280,13 +280,13 @@ fi
 
 tar  xf intltool-0.50.2.tar.gz && (cd intltool-0.50.2  && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure $GLOBAL_CONF && make && make install) || die "intltool build failed"
 if [ x$need_iconv != x ] ; then 
-    tar  xf gettext-0.18.1.1.tar.gz && (cd gettext-0.18.1.1  && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure --with-libiconv-prefix=$PREFIX --with-libintl-prefix=$PREFIX $GLOBAL_CONF && make && make install) || die "gettext build failed"
+    tar  xf gettext-0.18.1.1.tar.gz && (cd gettext-0.18.1.1  && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure --with-libiconv-prefix=$PREFIX $GLOBAL_CONF && make && make install) || die "gettext build failed"
 else
-    tar  xf gettext-0.18.1.1.tar.gz && (cd gettext-0.18.1.1  && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure --with-libintl-prefix=$PREFIX $GLOBAL_CONF && make && make install) || die "gettext build failed"
+    tar  xf gettext-0.18.1.1.tar.gz && (cd gettext-0.18.1.1  && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure $GLOBAL_CONF && make && make install) || die "gettext build failed"
 fi
 
 tar  xf tiff-4.0.1.tar.gz && (cd tiff-4.0.1 && CFLAGS="$GLOBAL_CFLAGS -DHAVE_APPLE_OPENGL_FRAMEWORK" LDFLAGS="$GLOBAL_LDFLAGS" ./configure $GLOBAL_CONF && make && make install) || die "tiff build failed"
-tar  xf libpng-1.5.10.tar.xz && (cd libpng-1.5.10 && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure --with-zlib-prefix=$PREFIX $GLOBAL_CONF && make && make install) || die "libpng build failed"
+tar  xf libpng-1.5.10.tar.xz && (cd libpng-1.5.10 && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure $GLOBAL_CONF && make && make install) || die "libpng build failed"
 tar  xf jpegsrc.v8d.tar.gz && (cd jpeg-8d && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure $GLOBAL_CONF && make && make install) || die "jpegsrc build failed"
 tar xf XML-Parser-2.41.tar.gz && (cd XML-Parser-2.41 && unset MACOSX_DEPLOYMENT_TARGET && perl Makefile.PL PREFIX=$PREFIX && make && make install) || die "XML-Parser build failed"
 tar xf XML-Simple-2.18.tar.gz && (cd XML-Simple-2.18 && unset MACOSX_DEPLOYMENT_TARGET && perl Makefile.PL PREFIX=$PREFIX && make && make install) || die "XML-Simple build failed"
@@ -300,7 +300,7 @@ tar xf libffi-3.0.10.tar.gz && (cd libffi-3.0.10 && CFLAGS=$GLOBAL_CFLAGS LDFLAG
 #
 # step one: build glib with everything specified so that pkg-config is not used or required
 #
-tar xf glib-2.32.2.tar.xz && (cd glib-2.32.2 && LDFLAGS=-L$PREFIX/lib CFLAGS=-I$PREFIX/include ZLIB_CFLAGS=-I$PREFIX/include ZLIB_LIBS=-I$PREFIX/lib LIBFFI_CFLAGS=-I$PREFIX/lib/libffi-3.0.10/include LIBFFI_LIBS="-L$PREFIX/lib -lffi" ./configure $GLOBAL_CONF --with-pcre=internal --disable-silent-rules && make && make install) && rm -rf glib-2.32.2 || die "glib build1 failed"
+tar xf glib-2.32.2.tar.xz && (cd glib-2.32.2 && LDFLAGS=-L$PREFIX/lib CFLAGS=-I$PREFIX/include ZLIB_CFLAGS=-I$PREFIX/include ZLIB_LIBS="-L$PREFIX/lib -lz" LIBFFI_CFLAGS=-I$PREFIX/lib/libffi-3.0.10/include LIBFFI_LIBS="-L$PREFIX/lib -lffi" ./configure $GLOBAL_CONF --with-pcre=internal --disable-silent-rules && make && make install) && rm -rf glib-2.32.2 || die "glib build1 failed"
 #
 # step two: build pkg-config with glib flags specified so that pkg-config is not used or required
 #
@@ -317,7 +317,7 @@ tar xf pkg-config-0.26.tar.gz && (cd pkg-config-0.26 && CFLAGS=$GLOBAL_CFLAGS LD
 # now we can start on the GTK stack itself
 # 
 tar xf atk-2.2.0.tar.bz2 && (cd atk-2.2.0 && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure $GLOBAL_CONF && make && make install) || die "atk build failed"
-tar xf gnome-common-2.34.0.tar.bz2 && (cd gnome-common-2.34.0 && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure $GLOBAL_CONF && make && make install) || die "gnome build failed"
+tar xf gnome-common-2.34.0.tar.bz2 && (cd gnome-common-2.34.0 && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure $GLOBAL_CONF && export MAKEFLAGS= make && MAKEFLAGS= make install) || die "gnome build failed"
 tar xf gtk-osx-docbook-1.0.tar.gz && (cd gtk-osx-docbook-1.0 && JHBUILD_PREFIX=$PREFIX make install) || die "gtk build failed"
 # gnome-doc-utils is not parallel-build safe so turn off make -j2
 tar xf gnome-doc-utils-0.20.6.tar.bz2 && (cd gnome-doc-utils-0.20.6 && PYTHONPATH=$PREFIX/lib/python2.7/site-packages CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure $GLOBAL_CONF --disable-scrollkeeper && PYTHONPATH=$PREFIX/lib/python2.7/site-packages MAKEFLAGS= make && PYTHONPATH=$PREFIX/lib/python2.7/site-packages MAKEFLAGS= make install) || die "gnome build failed"
