remove sudo from build-gtk-stack, by using PYTHONPATH to force installation location for python modules; use $PYVERS where appropriate (from robin gareus)
git-svn-id: svn://localhost/ardour2/branches/2.0-ongoing@14101 d708f5d6-7413-0410-9779-e7cbd77b26cf

diff --git a/tools/build-gtk-stack b/tools/build-gtk-stack
--- a/tools/build-gtk-stack
+++ b/tools/build-gtk-stack
@@ -177,7 +177,7 @@ if [ x$clean != x -o x$makespace != x ] ; then
     rm -rf `find . -maxdepth 1 -type d | grep -v -e "gtk+" -e "^.$"`
     # sudo required because of its use during the libxml2 install step
     if [ $clean ] ; then
-        sudo rm -rf $PREFIX
+        rm -rf $PREFIX
     fi
     exit 0
 fi
@@ -188,6 +188,9 @@ export MAKEFLAGS=-j$parallel
 PATH=$PREFIX/bin:$PATH
 
 PERLVERSION=`perl -e 'printf "%vd\n", $^V;'`
+
+PYVERS=`python --version 2>&1 | cut -d ' ' -f 2 | cut -b 1-3`
+export PYTHONPATH=$PREFIX/python${PYVERS}/site-packages/:${PYTHONPATH:+:$PYTHONPATH}
 
 OSX=
 
@@ -217,7 +220,7 @@ if uname -a | grep --silent arwin ; then
     if python --version | grep --silent '2\.7' ; then
         :
     else
-        PYTHON=/Library/Frameworks/Python.framework/Versions/2.7
+        PYTHON=/Library/Frameworks/Python.framework/Versions/${PYVERS}
     fi
 
     CAIRO_CONF="--enable-xlib=no --enable-quartz=yes --enable-xcb=no"
@@ -329,11 +332,7 @@ basic_builder flex
 basic_builder bison
 basic_builder expat
 
-#
-# libxml2 tries to install python modules in the system python folders and thus needs sudo for the install step. 
-# clean up afterwards to reset ownership on dirs and files created under $PREFIX as root
-# 
-tar xf $MOD_libxml2_local_tarball && (cd $MOD_libxml2_unpacked && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure $GLOBAL_CONF --with-zlib=$PREFIX ${PYTHON:+--with-python=$PYTHON} && make && sudo make install && sudo chown -R `whoami` $PREFIX) || die "libxml2 build failed"
+tar xf $MOD_libxml2_local_tarball && (cd $MOD_libxml2_unpacked && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure $GLOBAL_CONF --with-zlib=$PREFIX ${PYTHON:+--with-python=$PYTHON} && make && make install) || die "libxml2 build failed"
 
 basic_builder libxslt
 
@@ -418,8 +417,8 @@ basic_builder atk
 tar xf $MOD_gnomecommon_local_tarball && (cd $MOD_gnomecommon_unpacked && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure $GLOBAL_CONF && export MAKEFLAGS= make && MAKEFLAGS= make install) || die "gnome-common build failed"
 tar xf $MOD_gtkosxdocbook_local_tarball && (cd $MOD_gtkosxdocbook_unpacked && JHBUILD_PREFIX=$PREFIX make install) || die "gtk build failed"
 # gnome-doc-utils is not parallel-build safe so turn off make -j2
-tar xf $MOD_gnomedocutils_local_tarball && (cd $MOD_gnomedocutils_unpacked && PYTHONPATH=$PREFIX/lib/python2.7/site-packages CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure $GLOBAL_CONF --disable-scrollkeeper && PYTHONPATH=$PREFIX/lib/python2.7/site-packages MAKEFLAGS= make && PYTHONPATH=$PREFIX/lib/python2.7/site-packages MAKEFLAGS= make install) || die "gnome-doc-utils build failed"
-tar xf $MOD_gtkdoc_local_tarball && (cd $MOD_gtkdoc_unpacked && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure --disable-scrollkeeper --with-xml-catalog=$PREFIX/etc/xml/catalog --prefix=$PREFIX && PYTHONPATH=$PREFIX/lib/python2.7/site-packages make && make install) || die "gtk build failed"
+tar xf $MOD_gnomedocutils_local_tarball && (cd $MOD_gnomedocutils_unpacked && PYTHONPATH=$PREFIX/lib/python${PYVERS}/site-packages CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure $GLOBAL_CONF --disable-scrollkeeper && PYTHONPATH=$PREFIX/lib/python${PYVERS}/site-packages MAKEFLAGS= make && PYTHONPATH=$PREFIX/lib/python${PYVERS}/site-packages MAKEFLAGS= make install) || die "gnome-doc-utils build failed"
+tar xf $MOD_gtkdoc_local_tarball && (cd $MOD_gtkdoc_unpacked && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure --disable-scrollkeeper --with-xml-catalog=$PREFIX/etc/xml/catalog --prefix=$PREFIX && PYTHONPATH=$PREFIX/lib/python${PYVERS}/site-packages make && make install) || die "gtk build failed"
 tar xf $MOD_pixman_local_tarball && (cd $MOD_pixman_unpacked && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" sh ./autogen.sh --prefix=$PREFIX && make && make install) || die "pixman build failed"
 
 if [ x$OSX = x ] ; then
