significantly revisit build-gtk-stack to avoid building OR using libiconv/gettext on linux systems where it is part of glibc; also use a self-rolled tarball for gtk-engines rather than git
git-svn-id: svn://localhost/ardour2/branches/2.0-ongoing@13974 d708f5d6-7413-0410-9779-e7cbd77b26cf

diff --git a/tools/build-gtk-stack b/tools/build-gtk-stack
--- a/tools/build-gtk-stack
+++ b/tools/build-gtk-stack
@@ -98,7 +98,7 @@ if uname -a | grep --silent arwin ; then
     PANGO_CONF="--without-x"
     GTK_BACKEND=quartz
     AVOID_ICONV=
-    need_iconv=yes
+    explicit_intl=yes
 
 else 
 
@@ -111,7 +111,7 @@ else
     AVOID_ICONV="--with-libiconv=no"
     
     # normal linux platforms won't need this
-    need_iconv=
+    explicit_intl=
 
     # this is very crude versioning test
     python --version >/dev/null 2>&1
@@ -133,6 +133,7 @@ set -e
 
 export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
 GLOBAL_CONF="--prefix=$PREFIX"
+
 
 if [ ! -f xz-5.0.3.tar.bz2 ] ; then
     echo xz
@@ -287,10 +288,9 @@ if [ ! -f gobject-introspection-1.31.10.tar.xz ] ; then
     fetch_as_is http://ftp.gnome.org/pub/GNOME/sources/gobject-introspection/1.31/gobject-introspection-1.31.10.tar.xz
 fi
 
-if [ ! -d gtk-engines ] ; then
-    echo "gtk-engines (2.22 branch)"
-    git clone git://git.gnome.org/gtk-engines
-    (cd gtk-engines && git checkout --track -b gtk-engines-2-22 origin/gtk-engines-2-22)
+if [ ! -f gtk-engines-2.21.0.tar.gz ] ; then
+    echo "gtk-engines (via ardour.org)"
+    fetch_as_is http://ardour.org/files/gtk-engines-2.21.0.tar.gz
 fi
 
 if [ ! -d gtk+ ] ; then
@@ -352,18 +352,15 @@ tar  xf libxslt-1.1.26.tar.gz && (cd libxslt-1.1.26 && CFLAGS=$GLOBAL_CFLAGS LDF
 tar  xf readline-6.2.tar.gz && (cd readline-6.2  && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS -lncurses" ./configure $GLOBAL_CONF && make && make install) || die "readline build failed"
 
 #
-# Don't build and install libiconv on systems where it is part of glibc
+# Only build i18n libs on OS X 
+# This really needs to be a test for glibc with libintl builtin
 #
-if [ x$need_iconv != x ] ; then 
+if [ x$explicit_intl != x ] ; then
     tar  xf libiconv-1.14.tar.gz && (cd libiconv-1.14  && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure $GLOBAL_CONF && make && make install) || die "libiconv build failed"
+    tar  xf gettext-0.18.1.1.tar.gz && (cd gettext-0.18.1.1  && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure --with-included-gettext --with-libiconv-prefix=$PREFIX --enable-shared $GLOBAL_CONF && make && make install) || die "gettext build failed"
 fi
 
 tar  xf intltool-0.50.2.tar.gz && (cd intltool-0.50.2  && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure $GLOBAL_CONF && make && make install) || die "intltool build failed"
-if [ x$need_iconv != x ] ; then 
-    tar  xf gettext-0.18.1.1.tar.gz && (cd gettext-0.18.1.1  && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure --with-included-gettext --with-libiconv-prefix=$PREFIX --enable-shared $GLOBAL_CONF && make && make install) || die "gettext build failed"
-else
-    tar  xf gettext-0.18.1.1.tar.gz && (cd gettext-0.18.1.1  && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure --with-included-gettext --enable-shared $GLOBAL_CONF && make && make install) || die "gettext build failed"
-fi
 
 tar  xf tiff-4.0.1.tar.gz && (cd tiff-4.0.1 && CFLAGS="$GLOBAL_CFLAGS -DHAVE_APPLE_OPENGL_FRAMEWORK" LDFLAGS="$GLOBAL_LDFLAGS" ./configure $GLOBAL_CONF && make && make install) || die "tiff build failed"
 tar  xf libpng-1.5.13.tar.xz && (cd libpng-1.5.13 && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure $GLOBAL_CONF && make && make install) || die "libpng build failed"
@@ -390,11 +387,20 @@ tar xf glib-2.32.2.tar.xz && (cd glib-2.32.2 && LDFLAGS=-L$PREFIX/lib CFLAGS=-I$
 #
 # step two: build pkg-config with glib flags specified so that pkg-config is not used or required
 #
-tar xf pkg-config-0.26.tar.gz && (cd pkg-config-0.26 && GLIB_CFLAGS="-I$PREFIX/include/glib-2.0 -I$PREFIX/lib/glib-2.0/include" GLIB_LIBS="-L$PREFIX/lib -lglib-2.0 -lintl" ./configure --prefix=$HOME/gtk/inst && make && make install) && rm -rf pkg-config-0.26 || die "pkg-config build1 failed"
+if [ x$explicit_intl != x ] ; then
+    tar xf pkg-config-0.26.tar.gz && (cd pkg-config-0.26 && GLIB_CFLAGS="-I$PREFIX/include/glib-2.0 -I$PREFIX/lib/glib-2.0/include" GLIB_LIBS="-L$PREFIX/lib -lglib-2.0 -lintl" ./configure --prefix=$HOME/gtk/inst && make && make install) && rm -rf pkg-config-0.26 || die "pkg-config build1 failed"
+else
+    tar xf pkg-config-0.26.tar.gz && (cd pkg-config-0.26 && GLIB_CFLAGS="-I$PREFIX/include/glib-2.0 -I$PREFIX/lib/glib-2.0/include" GLIB_LIBS="-L$PREFIX/lib -lglib-2.0" ./configure --prefix=$HOME/gtk/inst && make && make install) && rm -rf pkg-config-0.26 || die "pkg-config build1 failed"
+fi
 # 
-# step three: rebuild glib (still need CFLAGS in order to find libintl)
+# step three: rebuild glib 
 #
-tar xf glib-2.32.2.tar.xz && (cd glib-2.32.2 && LDFLAGS="$GLOBAL_LDFLAGS -L$PREFIX/lib -lintl" CFLAGS="$GLOBAL_CFLAGS -I$PREFIX/include" ./configure --prefix=$HOME/gtk/inst && make && make install) || die "glib build failed"
+if [ x$explicit_intl != x ] ; then 
+    # still need CFLAGS and LDFLAGS in order to find libintl
+    tar xf glib-2.32.2.tar.xz && (cd glib-2.32.2 && LDFLAGS="$GLOBAL_LDFLAGS -L$PREFIX/lib -lintl" CFLAGS="$GLOBAL_CFLAGS -I$PREFIX/include" ./configure --prefix=$PREFIX && make && make install) || die "glib build failed"
+else 
+    tar xf glib-2.32.2.tar.xz && (cd glib-2.32.2 && LDFLAGS="$GLOBAL_LDFLAGS" CFLAGS="$GLOBAL_CFLAGS" ./configure --prefix=$PREFIX  && make V=1 && make install) || die "glib build failed"
+fi
 #
 # step four: rebuilding pkg-config now that glib is all set
 #
@@ -436,14 +442,12 @@ tar xf pango-1.29.5.tar.bz2 && (cd pango-1.29.5 && CFLAGS=$GLOBAL_CFLAGS LDFLAGS
 
 tar xf gdk-pixbuf-2.25.0.tar.xz && (cd gdk-pixbuf-2.25.0 && LDFLAGS="$GLOBAL_LDFLAGS -L$PREFIX/lib" CFLAGS="-I$PREFIX/include $GLOBAL_CFLAGS" ./configure $GLOBAL_CONF && make && make install) || die "gdk build failed"
 # gobject-introspection uses #include <libintl.h> and there's no way to force the "scanner" to look outside the system tree
-remove_libintl_h=
-if [ ! -f /usr/include/libintl.h ] ; then 
+if [ x$explicit_intl != x ] ; then
     sudo ln -s $PREFIX/include/libintl.h /usr/include
-    remove_libintl_h=yes
-fi
-tar xf gobject-introspection-1.31.10.tar.xz && (cd gobject-introspection-1.31.10 && LDFLAGS="$GLOBAL_LDFLAGS -L$PREFIX/lib -lintl" CFLAGS="-I$PREFIX/include $GLOBAL_CFLAGS" ./configure $GLOBAL_CONF && make && make install) || die "gobject build failed"
-if [ x$remove_libintl_h != x ] ; then
+    tar xf gobject-introspection-1.31.10.tar.xz && (cd gobject-introspection-1.31.10 && LDFLAGS="$GLOBAL_LDFLAGS -L$PREFIX/lib -lintl" CFLAGS="-I$PREFIX/include $GLOBAL_CFLAGS" ./configure $GLOBAL_CONF && make && make install) || die "gobject build failed"
     sudo rm /usr/include/libintl.h
+else
+    tar xf gobject-introspection-1.31.10.tar.xz && (cd gobject-introspection-1.31.10 && LDFLAGS="$GLOBAL_LDFLAGS" CFLAGS="$GLOBAL_CFLAGS" ./configure $GLOBAL_CONF && make && make install) || die "gobject build failed"
 fi
 #
 # now gtk itself
@@ -455,4 +459,4 @@ fi
 # now gtk-engines
 # 
 #
-(cd gtk-engines && CFLAGS="$GLOBAL_CFLAGS" LDFLAGS="$GLOBAL_LDFLAGS" sh autogen.sh --enable-maintainer-mode --prefix=$PREFIX --libdir=$PREFIX/lib && make && make install) || die "GTK-engines build failed"
+(tar xf gtk-engines-2.21.0.tar.gz && cd gtk-engines-2.21.0 && CFLAGS="$GLOBAL_CFLAGS" LDFLAGS="$GLOBAL_LDFLAGS" ./configure --prefix=$PREFIX/lib --libdir=$PREFIX/lib && make && make install) || die "GTK-engines build failed"
