define this_script_dir
git-svn-id: svn://localhost/ardour2/branches/2.0-ongoing@12373 d708f5d6-7413-0410-9779-e7cbd77b26cf

diff --git a/tools/build-ardour-stack b/tools/build-ardour-stack
--- a/tools/build-ardour-stack
+++ b/tools/build-ardour-stack
@@ -25,6 +25,7 @@ clean=
 makespace=
 parallel=2
 PREFIX=$HOME/a3/inst
+this_script_dir="`/usr/bin/dirname \"$0\"`"
 
 while [ $# -gt 0 ] ; do
    case $1 in
@@ -289,7 +290,7 @@ sndfile_patch=`ls $this_script_dir/misc-patches/libsndfile-1.0.25.patch`
 if [ x$OSX != x ] ; then
     # sndfile-play incorrectly includes <Carbon.h> which no longer works on Lion
     tar xf libsndfile-1.0.25.tar.gz && \
-        (set -e && cd libsndfile-1.0.25 && patch -p0 < $sndfile_patch CFLAGS="$GLOBAL_CFLAGS -I/System/Library/Frameworks/Carbon.framework/Headers" LDFLAGS="$GLOBAL_LDFLAGS" ./configure --prefix=$PREFIX --disable-silent-rules && make && make install) || die "sndfile build failed"
+        (set -e && cd libsndfile-1.0.25 && patch -p0 < $sndfile_patch && CFLAGS="$GLOBAL_CFLAGS -I/System/Library/Frameworks/Carbon.framework/Headers" LDFLAGS="$GLOBAL_LDFLAGS" ./configure --prefix=$PREFIX --disable-silent-rules && make && make install) || die "sndfile build failed"
     # samplerate incorrectly includes <Carbon.h> which no longer works on Lion
 tar xf libsamplerate-0.1.8.tar.gz && \
     (set -e && cd libsamplerate-0.1.8 && CFLAGS="$GLOBAL_CFLAGS -I/System/Library/Frameworks/Carbon.framework/Headers" LDFLAGS="$GLOBAL_LDFLAGS" ./configure --prefix=$PREFIX && make && make install) || die "samplerate build failed"
