bump versions of LV2 stack, based on current releases, nov 20th 2012
git-svn-id: svn://localhost/ardour2/branches/2.0-ongoing@13539 d708f5d6-7413-0410-9779-e7cbd77b26cf

diff --git a/tools/build-ardour-stack b/tools/build-ardour-stack
--- a/tools/build-ardour-stack
+++ b/tools/build-ardour-stack
@@ -189,29 +189,29 @@ if [ ! -d LRDF ] ; then
     git clone git://github.com/swh/LRDF.git
 fi
 
-if [ ! -f lv2-1.0.0.tar.bz2 ] ; then
+if [ ! -f lv2-1.2.0.tar.bz2 ] ; then
     echo LV2
-    fetch_as_is http://lv2plug.in/spec/lv2-1.0.0.tar.bz2
+    fetch_as_is http://lv2plug.in/spec/lv2-1.2.0.tar.bz2
 fi
-if [ ! -f serd-0.14.0.tar.bz2 ] ; then
+if [ ! -f serd-0.18.0.tar.bz2 ] ; then
     echo Serd
-    fetch_as_is http://download.drobilla.net/serd-0.14.0.tar.bz2
+    fetch_as_is http://download.drobilla.net/serd-0.18.0.tar.bz2
 fi
-if [ ! -f sord-0.8.0.tar.bz2 ] ; then
+if [ ! -f sord-10.4.tar.bz2 ] ; then
     echo Sord
-    fetch_as_is http://download.drobilla.net/sord-0.8.0.tar.bz2
+    fetch_as_is http://download.drobilla.net/sord-0.10.4.tar.bz2
 fi
-if [ ! -f sratom-0.2.0.tar.bz2 ] ; then
+if [ ! -f sratom-0.4.0.tar.bz2 ] ; then
     echo Sratom
-    fetch_as_is http://download.drobilla.net/sratom-0.2.0.tar.bz2
+    fetch_as_is http://download.drobilla.net/sratom-0.4.0.tar.bz2
 fi
-if [ ! -f lilv-0.14.2.tar.bz2 ] ; then
+if [ ! -f lilv-0.14.4.tar.bz2 ] ; then
     echo Lilv
-    fetch_as_is http://download.drobilla.net/lilv-0.14.2.tar.bz2
+    fetch_as_is http://download.drobilla.net/lilv-0.14.4.tar.bz2
 fi
-if [ ! -f suil-0.6.4.tar.bz2 ] ; then
+if [ ! -f suil-0.6.6.tar.bz2 ] ; then
     echo Suil
-    fetch_as_is http://download.drobilla.net/suil-0.6.4.tar.bz2
+    fetch_as_is http://download.drobilla.net/suil-0.6.6.tar.bz2
 fi
 if [ ! -f curl-7.25.0.tar.bz2 ] ; then
     echo curl
@@ -327,18 +327,18 @@ tar xf isodate-0.4.0.tar.gz && \
   sed 's/glibtoolize/libtoolize/g' < autogen.sh > ag.sh && mv ag.sh autogen.sh && \
   CFLAGS="$GLOBAL_CFLAGS -I$PREFIX/include" LDFLAGS="$GLOBAL_LDFLAGS" sh ./autogen.sh --prefix=$PREFIX && make && make install) || die "LRDF build failed"
 
-tar xf lv2-1.0.0.tar.bz2 && \
-    (set -e && cd lv2-1.0.0 && unset MACOSX_DEPLOYMENT_TARGET && ./waf configure --prefix=$PREFIX --copy-headers && ./waf build && sudo ./waf install) || die "LV2 build failed"
-tar xf serd-0.14.0.tar.bz2 && \
-    (set -e && cd serd-0.14.0 && ./waf configure --prefix=$PREFIX && ./waf build && ./waf install) || die "serd build failed"
-tar xf sord-0.8.0.tar.bz2 && \
-    (set -e && cd sord-0.8.0 && ./waf configure --prefix=$PREFIX  && ./waf build && ./waf install) || die "sord build failed"
-tar xf sratom-0.2.0.tar.bz2 && \
-    (set -e && cd sratom-0.2.0 && ./waf configure --prefix=$PREFIX && ./waf build && ./waf install) || die "sratom build failed"
-tar xf lilv-0.14.2.tar.bz2 && \
-    (set -e && cd lilv-0.14.2 && ./waf configure --prefix=$PREFIX --default-lv2-path='~/.lv2:/usr/local/lib/lv2:/usr/local/lib64/lv2:/usr/lib/lv2:/usr/lib64/lv2' && ./waf build && ./waf install) || die "lilv build failed"
-tar xf suil-0.6.4.tar.bz2 && \
-    (set -e && cd suil-0.6.4 && CFLAGS="-I$PREFIX/include" ./waf configure --prefix=$PREFIX && ./waf && ./waf install) || die "suil build failed"
+tar xf lv2-1.2.0.tar.bz2 && \
+    (set -e && cd lv2-1.2.0 && unset MACOSX_DEPLOYMENT_TARGET && ./waf configure --prefix=$PREFIX --copy-headers && ./waf build && sudo ./waf install) || die "LV2 build failed"
+tar xf serd-0.18.0.tar.bz2 && \
+    (set -e && cd serd-0.18.0 && ./waf configure --prefix=$PREFIX && ./waf build && ./waf install) || die "serd build failed"
+tar xf sord-0.10.4.tar.bz2 && \
+    (set -e && cd sord-0.10.4 && ./waf configure --prefix=$PREFIX  && ./waf build && ./waf install) || die "sord build failed"
+tar xf sratom-0.4.0.tar.bz2 && \
+    (set -e && cd sratom-0.4.0 && ./waf configure --prefix=$PREFIX && ./waf build && ./waf install) || die "sratom build failed"
+tar xf lilv-0.14.4.tar.bz2 && \
+    (set -e && cd lilv-0.14.4 && ./waf configure --prefix=$PREFIX --default-lv2-path='~/.lv2:/usr/local/lib/lv2:/usr/local/lib64/lv2:/usr/lib/lv2:/usr/lib64/lv2' && ./waf build && ./waf install) || die "lilv build failed"
+tar xf suil-0.6.6.tar.bz2 && \
+    (set -e && cd suil-0.6.6 && CFLAGS="-I$PREFIX/include" ./waf configure --prefix=$PREFIX && ./waf && ./waf install) || die "suil build failed"
 
 # two post-install hacks
 
