a different approach tobuild VM python issues
git-svn-id: svn://localhost/ardour2/branches/2.0-ongoing@14166 d708f5d6-7413-0410-9779-e7cbd77b26cf

diff --git a/tools/build-gtk-stack b/tools/build-gtk-stack
--- a/tools/build-gtk-stack
+++ b/tools/build-gtk-stack
@@ -337,11 +337,19 @@ basic_builder flex
 basic_builder bison
 basic_builder expat
 
-export BASH_ENV=$HOME/setvx
+#
+# this will fail to build python modules if Python is not a system install, so we need to supply --with-python in that case
+#
 
-tar xf $MOD_libxml2_local_tarball && (cd $MOD_libxml2_unpacked && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure $GLOBAL_CONF --with-zlib=$PREFIX && make && make install) || die "libxml2 build failed"
+pythondir=`which python`
+pythondir=`dirname $pythondir`
+WITHPYTHON=
 
-unset BASH_ENV
+if [ x$pythondir != /usr/bin ] ; then
+    WITHPYTHON=--with-python=$pythondir
+fi
+
+tar xf $MOD_libxml2_local_tarball && (cd $MOD_libxml2_unpacked && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure $GLOBAL_CONF $WITHPYTHON --with-zlib=$PREFIX && make && make install) || die "libxml2 build failed"
 
 basic_builder libxslt
 
