don't try to set PYTHON or use --with-python, just check we have python version >= 2.6 and get on with it; avoids incorrect attempt to install into system locations
git-svn-id: svn://localhost/ardour2/branches/2.0-ongoing@14127 d708f5d6-7413-0410-9779-e7cbd77b26cf

diff --git a/tools/build-gtk-stack b/tools/build-gtk-stack
--- a/tools/build-gtk-stack
+++ b/tools/build-gtk-stack
@@ -217,10 +217,15 @@ if uname -a | grep --silent arwin ; then
     # suitably new (2.7 or later) version of Python's framework
     #
     # this is very crude versioning test
-    if python --version | grep --silent '2\.7' ; then
-        :
+    if python --version 2>&1 | grep --silent '2\.7' ; then
+	:
     else
-        PYTHON=/Library/Frameworks/Python.framework/Versions/${PYVERS}
+	if python --version 2>&1 | grep --silent '2\.6' ; then
+	    :
+	else
+	    echo "You need at least Python 2.6 to run this script"
+	    exit 1
+	fi
     fi
 
     CAIRO_CONF="--enable-xlib=no --enable-quartz=yes --enable-xcb=no"
@@ -332,7 +337,7 @@ basic_builder flex
 basic_builder bison
 basic_builder expat
 
-tar xf $MOD_libxml2_local_tarball && (cd $MOD_libxml2_unpacked && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure $GLOBAL_CONF --with-zlib=$PREFIX ${PYTHON:+--with-python=$PYTHON} && make && make install) || die "libxml2 build failed"
+tar xf $MOD_libxml2_local_tarball && (cd $MOD_libxml2_unpacked && CFLAGS=$GLOBAL_CFLAGS LDFLAGS="$GLOBAL_LDFLAGS" ./configure $GLOBAL_CONF --with-zlib=$PREFIX && make && make install) || die "libxml2 build failed"
 
 basic_builder libxslt
 
